// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlldULuBOs9Z0vXqjPPHLFz-yVIAMUgBU',
    appId: '1:751854559088:web:fd4df7d1f3acc31c0ab9b5',
    messagingSenderId: '751854559088',
    projectId: 'skartner-af3bf',
    authDomain: 'skartner-af3bf.firebaseapp.com',
    storageBucket: 'skartner-af3bf.appspot.com',
    measurementId: 'G-K5BCMXYREF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAubETm6m6UJPLhAnAJabuBKtB2e4yQ2wA',
    appId: '1:751854559088:android:7dabbfb0b61840fa0ab9b5',
    messagingSenderId: '751854559088',
    projectId: 'skartner-af3bf',
    storageBucket: 'skartner-af3bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4q6gRB2Hmu9na3AN4wqcrysjqAnswzPQ',
    appId: '1:751854559088:ios:bfefd3a8d8acac100ab9b5',
    messagingSenderId: '751854559088',
    projectId: 'skartner-af3bf',
    storageBucket: 'skartner-af3bf.appspot.com',
    iosClientId: '751854559088-ajmlaq0lcmhuh6988f189aqkhlq356hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.skartnerApp',
  );
}
